---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  datasource:
    type: prometheus
    name: Prometheus
    access: proxy
    isDefault: true
    url: http://kube-prometheus-stack-prometheus.observability.svc:9090
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: alertmanager
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  datasource:
    type: alertmanager
    name: Alertmanager
    access: proxy
    jsonData:
      implementation: prometheus
    url: http://kube-prometheus-stack-alertmanager.observability.svc:9093
