---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seerr-secret
  namespace: media
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: seerr-secret
    creationPolicy: Owner
  data:
    - secretKey: API_KEY
      remoteRef:
        key: homelab-media-api-keys/SEERR_API_KEY
