---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: autobrr-secret
  namespace: media
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: autobrr-secret
    creationPolicy: Owner
  data:
    - secretKey: AUTOBRR__SESSION_SECRET
      remoteRef:
        key: homelab-media-api-keys/AUTOBRR_SESSION_SECRET
