apiVersion: v1
kind: Secret
metadata:
  name: media-arr-api
  namespace: media
stringData:
  SONARR_API_KEY: ENC[AES256_GCM,data:ib6xdeNnhb8XI5vggNj0xLuX2bzPWJrawT6myZnLL+0=,iv:7r4Jia43rdVFPKmTc9IhbFxlr+HUBRFldLStBqUVDnc=,tag:c8L8li8PGihg/jkCRSTG7A==,type:str]
  RADARR_API_KEY: ENC[AES256_GCM,data:myUkrgn3doNX8EbvfhzL2LG6gVm/Lyk97AGxk+RcMDI=,iv:bELu9n3noNaOm+BK5q7RZnVkkZqQlxbC0AY4FyA4hB4=,tag:KtyE4fWKRz/3C7sh3Eyz+A==,type:str]
  PROWLARR_API_KEY: ENC[AES256_GCM,data:RGvA1+h0GgKScZOVwAb56lXQ4gUvpP6bFygsB86Zj14=,iv:gBLAKgZYWkSKhEdjGA5yLuMSqkou9AoBanNtzvfbX34=,tag:nImnjIrGefie/9KqFpkriw==,type:str]
sops:
  age:
    - recipient: age16zf0xkqzqarwgrnrj8eqv2eaylnsuph2npuqq90esxzh8zt3t3zs5z3y4j
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlSkN6MUM3TlZFWDR1aGpk
        K2xYMkJXTlJ1ZWdIeGlGeE5NMlNXUHNWQ3pZCmRhTEdwQU1HVC9pRmNNK2VLUkpy
        UFNGWEdLbWxtdlBHdTdMWXlwTWZwdWcKLS0tIFNKTXhKYm9RaUNmWkpSRjYzUUJw
        YmxCSmVHcURtQktLQkxmMk9PS09ZZDQKHnJf7+YaYdDQEMeXIpwWjRGJ0IB0OTZJ
        oY1D6Q2ZiRzGLEL0q4JwNOFxoC0k2za2avEJygndQAPkRqNHPJZp2w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-22T21:26:19Z"
  mac: ENC[AES256_GCM,data:oJar5ebRqG+vLHwUXm22nvOw4osT85JntSCyE76b3Km5vsHhf6F11PAidnE4Xe6Xzv26okGZGg6QulFgZA6XYt+2Rv3SCrE0YnSfn9vHdIUfZ31u/xMJqpKNLIjm3GibTdIw1d0DAabAQoiGXN0e2RL6y+89GVTrq39COkopj1c=,iv:bztDBS/dvWNrQnYrnFnTaugk8ghRA6dnhOIFiPvaivM=,tag:l4UUePQ77h9kFp3zMwYtkg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
