---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tuppr
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/compare-options: ServerSideDiff=false
spec:
  project: kubernetes
  sources:
    - repoURL: "https://github.com/SuperMiguel/home-ops.git"
      targetRevision: main
      ref: repo
    - repoURL: oci://ghcr.io/home-operations/charts/tuppr
      chart: tuppr
      targetRevision: 0.1.3
      helm:
        releaseName: tuppr
        valueFiles:
          - $repo/kubernetes/apps/system-upgrade/tuppr/values.yaml
  destination:
    name: in-cluster
    namespace: system-upgrade
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    retry:
      limit: 2
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 5m
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true
      - RespectIgnoreDifferences=true
