---
# https://gethomepage.dev/configs/bookmarks

- Homelab:
    - Argo CD:
        - abbr: CD
          href: https://argo.veliz.cc
    - Gatus:
        - abbr: GS
          href: https://gatus.veliz.cc
    - Grafana:
        - abbr: GF
          href: https://grafana.veliz.cc/d/veliz-home
    - Longhorn:
        - abbr: LH
          href: https://longhorn.veliz.cc
    - MinIO:
        - abbr: S3
          href: https://minio.veliz.cc
    - Home Assistant:
        - abbr: HA
          href: https://hass.veliz.cc

- Dev:
    - home-ops:
        - abbr: HO
          href: https://github.com/SuperMiguel/home-ops
    - Super-Veliz-Network:
        - abbr: NET
          href: https://github.com/SuperMiguel/Super-Veliz-Network
