---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings

title: Super Homepage
color: stone
base: https://home.veliz.cc
target: _blank
fiveColumns: true

layout:
  Compute:
    style: row
    columns: 4
  Network:
    style: row
    columns: 3
  Home automation:
    style: row
    columns: 3
  AI:
    style: row
    columns: 2
  Kubernetes:
    style: row
    columns: 2
  Observability:
    style: row
    columns: 3
  Media:
    style: row
    columns: 3
