---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: Super Homepage
color: stone
base: https://home.veliz.cc
target: _blank
fiveColumns: true

layout:
    Proxmox Cluster:
      style: row
      columns: 4
    Kubernetes:
      style: column
    Media:
      style: row
      columns: 3
