controllers:
  echo:
    strategy: RollingUpdate
    containers:
      app:
        image:
          repository: ghcr.io/mendhak/http-https-echo
          tag: 39
        env:
          HTTP_PORT: 80
          LOG_WITHOUT_NEWLINE: true
          LOG_IGNORE_PATH: /healthz
          PROMETHEUS_ENABLED: true
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /healthz
                port: 80
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /healthz
                port: 80
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        resources:
          requests:
            cpu: 10m
          limits:
            memory: 64Mi
defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
service:
  app:
    ports:
      http:
        port: 80
serviceMonitor:
  app:
    endpoints:
      - port: http
route:
  app:
    hostnames:
      - echo.veliz.cc
    parentRefs:
      - name: envoy-internal
        namespace: network
        sectionName: https
    rules:
      - backendRefs:
          - identifier: app
            port: 80
sops:
  age:
    - recipient: age16zf0xkqzqarwgrnrj8eqv2eaylnsuph2npuqq90esxzh8zt3t3zs5z3y4j
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVMFprN0pLNkMxYVp6SHpH
        ZngwOU5zZXRUOHpabzNacE1BZXY5aGgzVncwCjBXZ3lRRVZOSTVlUlhlRjNmSEF2
        QjZGOTZySUdyQ3MzdVZWNEg2NjAxMzgKLS0tIEVjT1I0SDcwSlRZTmttN0txNHow
        QXRHcUJ6L0NqYy9MKzZhSnRUbnBIcnMK1GbE2wSokEibJ90HqqcfVdfq5sCnEhU+
        BgqYtEiQ7Oe3Wxvcl7qcL1bTjkx9wpfr0ukdHQLurR73dfDj6xBp2w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-22T04:13:18Z"
  mac: ENC[AES256_GCM,data:UwG1jnZ/omjmGGyt4A/Rq7obmklFzmW07qGOjDPH3qe9qHvI2Dg8AxR7LxhSEEc/NaiUWaCl6Ie1z+ZoCENyqVTYtD4ZmlcYhgUixweWNb02CmMCQVkwcPG2SBsQXSte6kxEzCRjg7TYsMpNcf1GggshFbpfApuyEFIws6JerTw=,iv:SIflheodjxmoxDQkkoxEPLAL+0S6Ed6n/l6wtuvGjXo=,tag:rzknt++b/48FMZJGdTLNOQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
