apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:yv1JRVrykXaPhZwGvQ6eTebrYJSul3nrNb71AyQ0/0tNKONTnwrlSk/OFyThnMWkD11wyUE=,iv:aMUvLD9Om08hSPIQkbhZAiEURtiTYJkCzvjd/VFAGbs=,tag:kN6YV/70cRXNSGhFOCx3Dw==,type:str]
sops:
  age:
    - recipient: age16zf0xkqzqarwgrnrj8eqv2eaylnsuph2npuqq90esxzh8zt3t3zs5z3y4j
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVNlllekZZRU9yd2xVOVJH
        cGZLL1lzZCtvWDRYTFZCWmlXRmhZejdNTlY0CkxVQmlKeDk3MDdEVS9QUlVtWnlh
        OER6OTVMeU90SkNNeEVEMVZkRGFPNWsKLS0tIDNMZGRpM0grY2RicEJhaXdOZXNF
        ektROE42L3hMbHc5QXJPcXlNZUFJRzgKGq5ATQ6r5BjtEkcDnxEdH7G+RjMmTNv1
        16k5eEzM8vZgiqX/gXX11kUSTWReo7vzcnqn5eKWFSwf2O4xK76HrA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-22T04:13:18Z"
  mac: ENC[AES256_GCM,data:dV6sA315gihLzT2OfupfvBlfhLa7Aqig6GtjNCqPSKF2reGXGiAxoWG7ayRCK/X7MlVT5Bfn53PFXPQF+P6CDqvAhYMKZa06mKa7GeIYg0gOO3vz18PX8CNEyHPdl6lECMPZvUekG1Ns7m94RecJqB9HXe+PlktgQc1OTUY8+4c=,iv:AWbYzM0wc18YwTdsidjScYs5SB+kVXWkmUPMQ0H+ZxA=,tag:2h+saUljlKGYMkcb2TOHxA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
