---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/compare-options: ServerSideDiff=false
spec:
  project: kubernetes
  sources:
    - repoURL: "https://github.com/SuperMiguel/home-ops.git"
      targetRevision: main
      ref: repo
    - repoURL: oci://ghcr.io/fluent/helm-charts/fluent-bit
      chart: fluent-bit
      targetRevision: 0.57.2
      helm:
        releaseName: fluent-bit
        valueFiles:
          - $repo/kubernetes/apps/observability/fluent-bit/values.yaml
  destination:
    name: in-cluster
    namespace: observability
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    retry:
      limit: 2
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 5m
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true
      - RespectIgnoreDifferences=true
