controllers:
  prowlarr:
    strategy: RollingUpdate
    containers:
      app:
        image:
          repository: lscr.io/linuxserver/prowlarr
          tag: 1.37.0
        env:
          TZ: America/New_York
          PUID: "1000"
          PGID: "1000"
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /
                port: 9696
              initialDelaySeconds: 45
              periodSeconds: 10
              timeoutSeconds: 5
              failureThreshold: 5
          readiness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /
                port: 9696
              initialDelaySeconds: 30
              periodSeconds: 10
              timeoutSeconds: 5
              failureThreshold: 5
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
              - ALL
        resources:
          requests:
            cpu: 50m
          limits:
            memory: 768Mi
defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 5Gi
    storageClass: longhorn
    globalMounts:
      - path: /config
service:
  app:
    ports:
      http:
        port: 9696
route:
  app:
    hostnames:
      - prowlarr.veliz.cc
    parentRefs:
      - name: envoy-external
        namespace: network
        sectionName: https
    rules:
      - backendRefs:
          - identifier: app
            port: 9696
sops:
  age:
    - recipient: age16zf0xkqzqarwgrnrj8eqv2eaylnsuph2npuqq90esxzh8zt3t3zs5z3y4j
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1K1VnMklSbFRFTnVmcjBX
        am11aDlIUk4vb0xJTUI3aGlTSiszMi9CckNFCjA0REVxTTVBcGkzQU1SUFBjMHBE
        NFlJZnhLb1JTYW12SW1YRWtTN3VaejAKLS0tIEpCU1ZSVldKRDdRSXBJa3FRNmJO
        TW84M2ZrRWVrbkNMWktYSjhRYzJadlkKv8g1RVkJQqF/wS7lDQnDCQ32vphvLA+G
        x4ZhSFBkxXgZ5GlKPgwYU7OiZmeddglCjZOTwsKPE6744CjIBzcPPA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-22T19:29:29Z"
  mac: ENC[AES256_GCM,data:ssZEcK/LwjCB7g0NuHF8mIdS8oKYstH08eDpnvp+nFbJyewhy19iAPGiFRn8jWk09qON6Qljmm3x2tWhxdTd85nPo3h3Evc+3/xhar3knUu/e2NP1NR6Ipsfi+2Lc9dXOAIQT10hqcy4qOvhC57vP3VF9YkdsEPb1cNGf9fWx+I=,iv:ymArBYqmMxNMIuLmAOxtXSmZYVIGEf3nJegkO6IBoVw=,tag:v2zUQ2JYHY8cjk6MoT0fFA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
