apiVersion: v1
kind: Secret
metadata:
  name: helm-secrets-private-keys
stringData:
  key.txt: ENC[AES256_GCM,data:IkAtQklpwVRkc+E8oNK11qamviNbF+A6vOGjAH40FTAdefgjofFuPvQSizBF+uzZRt64eY9RGLnuYJSe8YDxgUSwOgKw0h+EvKOJ,iv:/v8HGivAdXgn0uDj3gk0zFR6BqAw7tgWT6kAnuJfxsY=,tag:gYQs/+8AvnpRUrfHrOyr6w==,type:str]
sops:
  age:
    - recipient: age16zf0xkqzqarwgrnrj8eqv2eaylnsuph2npuqq90esxzh8zt3t3zs5z3y4j
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWGZJWi9QbE8wNFZoN29Y
        aENxMVlKN1dJZ3ozVG82cXRaU0lHWGhVT2lRClNRYXUyenVJVkZLQzB6cGlBWUhM
        THB2WWo3WksxRDhWMm5EYkcwTW9GVHcKLS0tIGhTYzZHZkliSVlwSXRhdkNhcE9N
        T0x3dVgxb1FvVTQyWVNYOE1SMkZ0SjgKjr0K949knJignatSJW4E59MkDsPlIU4k
        5EXv8edTa5ymJ/ig4GiKzw4iBWI9W5LAtmyMXA+32uW4mPo8FdN2Kg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-22T04:13:18Z"
  mac: ENC[AES256_GCM,data:L/9OSpKkY4PIQncPQuuQhhxyO+o2SIDhsxRLRcoysrRcS6eHTD27XZsvDPy6MU5FArQJtLK4JAuHCdqmNZjg7Hv1OueXoR4z4GA6HpqQsuyzNYSKrLhsFMhYUT2ktT5qR2nFfeDRDrKTeq/Gz0forTcay00EIhAe2qYWPTkIPxQ=,iv:jZ678OTQ/7k86qrjM+4wZF8xP2aUBL1v2oJBV4X8GdI=,tag:QItPit39d/PYJpeg0cbdCQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
