apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:jhHnPL0Ty0S4wG8OTMzlroXOvWjrOMIZUiePseCYmS2g2ZM3IeN3sVIdEk4f1DenKqU4OPZXnssq3qMwxivF8S4/vKZPGFkCRn/WPACEw56FpW2B5lGRbbm7Qz/erxAFXhDbd9c0Yj5EL+F3c6MVmhzg5UwDHIXXT60Qewe7mTuY/qM73SWjy30Gt7rnsqu/eErY/7Q/EUvSWkAyhijSKMHSMg48dXamFWtWtnMckSxTRfwr,iv:NFgUbiLeQzb6MArl0U2Xa5G2+nKlMS8f2w033+jH3cU=,tag:IhKbT1J2IZHMQWomfmo5UQ==,type:str]
sops:
  age:
    - recipient: age16zf0xkqzqarwgrnrj8eqv2eaylnsuph2npuqq90esxzh8zt3t3zs5z3y4j
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjWG01anNkbDI0b0NKWWZ2
        djhCM1BhZHFjc2lzMFFtZVROUkJWL2RGYUZVCkowWFcvaGllM1k0Rm95dCtrWXcw
        VEJhaDZCKzlwOEttdlRJdjBqZlQ4U0EKLS0tIDl5MVQ4QUFlWWRzZHZ1UE1XNVNV
        L1VLY1NGUWs3QS83cHBiWmpONUwybWMKVJ7fZxK9SLtJ5isX+cN2zlgsEntbY5hr
        nn0W/3gFH2q/KWhwMcbMYeHN7zSVYgdkt/3IwjqizdrVn8b018VgpQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-22T04:13:18Z"
  mac: ENC[AES256_GCM,data:EMDRdWs2jQtxcKOgwXlvmSHzgY89HRh0k+KfeuXhPVs04+/FV/irHgvXXEjeUKa1TYTs84P/jCNnpG/Aa9/lYDj11d0EIrcgAuHhBM9J5Ls2e6WYBvYygBw1JTav3eg1LfsP5LlYpWUfHoaWw/9g9kxQNFyvZgRno6aTVVgM2pE=,iv:ygJnCHw/bjD4/DLZdyhx0gX0nISSOgcfLzIZfRKbg7E=,tag:T9p41jTLUJeZhhVuQmSTsg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
