controllers:
  tautulli:
    strategy: RollingUpdate
    containers:
      app:
        image:
          repository: lscr.io/linuxserver/tautulli
          tag: 2.15.3-ls163
        env:
          TZ: America/New_York
          PUID: "1000"
          PGID: "1000"
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /
                port: 8181
              initialDelaySeconds: 45
              periodSeconds: 10
              timeoutSeconds: 5
              failureThreshold: 5
          readiness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /
                port: 8181
              initialDelaySeconds: 30
              periodSeconds: 10
              timeoutSeconds: 5
              failureThreshold: 5
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
              - ALL
        resources:
          requests:
            cpu: 50m
          limits:
            memory: 768Mi
defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 5Gi
    globalMounts:
      - path: /config
service:
  app:
    ports:
      http:
        port: 8181
route:
  app:
    hostnames:
      - tautulli.veliz.cc
    parentRefs:
      - name: envoy-external
        namespace: network
        sectionName: https
    rules:
      - backendRefs:
          - identifier: app
            port: 8181
sops:
  age:
    - recipient: age16zf0xkqzqarwgrnrj8eqv2eaylnsuph2npuqq90esxzh8zt3t3zs5z3y4j
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Qk1KamdicGxKR3FxMDhu
        bnZEZHJPNFY2d0FhM2ZNQkdDK0E2SkJzMkJvCjByelBCeGk3RGVnVllEeU1LRFB0
        eTR5S3pOQVhsakZCa2ZmKzBrNjZUTmMKLS0tIFh1ZCtQdkUwOVZycWI0TG1oR0xK
        NmtjSjFmeHdPSDJQWkp2ODljWlh6elUKaAD6soqmqCYcWxLmS33kNinj6gKDPdNl
        xrdZbSTlJslO9lVMf/GLeLb/I7Bny9BU4/L2UMSHSTmBnf04a6B21Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-22T12:25:48Z"
  mac: ENC[AES256_GCM,data:gemGBHZIlIhOVg1lSlL5mUlXlVdJtuMTqkGjeOWBTnJnqlUIPGaDV6PXiAS9gAQsduhQZhgFIcDy/IwX8Mgy96hefFnGEjx0YyYEQOrcERRNzVjRkM3q8KFwBNC4yd3U71bSmbrHKBvpp6InHFNFoCQ5v2vkZjGt8kQt74/TtMc=,iv:0wTuB+zwYpgH8kCNVTnZW4Zs1RzpXBm07lM37FD+i8w=,tag:7c0yamnwT8bV3RKnftCbMw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
