controllers:
  homepage:
    strategy: RollingUpdate
    containers:
      app:
        image:
          repository: ghcr.io/gethomepage/homepage
          tag: v1.1.0
        env:
          HOMEPAGE_ALLOWED_HOSTS: home.veliz.cc
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /api/healthcheck
                port: 3000
                httpHeaders:
                  - name: Host
                    value: home.veliz.cc
              initialDelaySeconds: 10
              periodSeconds: 10
              timeoutSeconds: 3
              failureThreshold: 3
          readiness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /api/healthcheck
                port: 3000
                httpHeaders:
                  - name: Host
                    value: home.veliz.cc
              initialDelaySeconds: 5
              periodSeconds: 10
              timeoutSeconds: 3
              failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
              - ALL
        resources:
          requests:
            cpu: 25m
          limits:
            memory: 512Mi
defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 568
    runAsGroup: 568
    fsGroup: 568
service:
  app:
    ports:
      http:
        port: 3000
configMaps:
  services:
    data:
      services.yaml: ENC[AES256_GCM,data:R+trx6ja8mSZKD2iaWViYwTxYX0MNhFNyC3Fh/XkQ1G3RrfmanSXqtUuU/DW7hQ9zaqp6DWsWIH/DztcdC5NvPAbl362BvDdizMss7pLLNuy5WV3EfcjzQB9sxQwO6TEJ1VHN/we4IbKhUWc16uQ/iYDum7dLiiLCR1fL2MVGXd3Vqhk9ak9CxJLpArvIWzXTg1ZwQdgKRBWuf5fg0wqgX3V7iQW1s441IqnblH1NwxSBnHv5wzzaKuN5l9AwkcCU0jvgDrSrna/hisBc5ZWEf6dL0wj08IPvc8rOmtycOA40m9hku/G2qJEgKUU1QxBPY4mbQbvJmdi1uqUGMY/vBTeKcJvIR9+w3YVCW6qrZbiu0JhAA3poL0gOIF+gwLmpRhwF3WbI5GVMRqw1SAY8NzKJ9b+nYnjn870ckk3dXK6IeAXHx9e/6tIcAWaaYgbvLkcf02m+IFWTnPnyp+WkX4hST0=,iv:g1R0/ajIsN4Dhy2cOWglnuV3A9WLvrz3pNugOttD8ww=,tag:mBRaaYNRY6E3or3fG0aVNg==,type:str]
      settings.yaml: ENC[AES256_GCM,data:eDx1zb2JM1n5rabtcdmxxw==,iv:3i1hhmtxScIPgf8mDCABWAAcn4j3uFBGKfYR69TH5vw=,tag:jaIqnCRqRY4L0DhXHHsPJw==,type:str]
persistence:
  config-workspace:
    enabled: true
    type: emptyDir
    globalMounts:
      - path: /app/config
  services:
    type: configMap
    identifier: services
    globalMounts:
      - path: /app/config/services.yaml
        subPath: services.yaml
      - path: /app/config/settings.yaml
        subPath: settings.yaml
route:
  app:
    hostnames:
      - home.veliz.cc
    parentRefs:
      - name: envoy-external
        namespace: network
        sectionName: https
    rules:
      - backendRefs:
          - identifier: app
            port: 3000
sops:
  age:
    - recipient: age16zf0xkqzqarwgrnrj8eqv2eaylnsuph2npuqq90esxzh8zt3t3zs5z3y4j
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Mzd2dGk0RFdkUTVaMzVt
        VThoemMvTGhnV1pOd21nQlBGazR3N3ZGdWlZCjNDaGppaFRsYzEyWExBZm1WVDgv
        Wi9XWkx4REVrWUtZWVplMEhWWm4xcm8KLS0tIHZBNDY2M1BvVWRHVmtSKzNFMVZK
        c2tmODFpaDlyYW9iaGhIMkJLNmFIZDAKDVn1pPaTKx8ZwjvMg2GZO3YZJciqv/Yc
        TX2ozBIeflybUcFWoQid29fHR6gqtO9k1/dmuXJvNlVkxi9Ubtvhpw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-22T11:42:59Z"
  mac: ENC[AES256_GCM,data:YbpcgJ5v8UNioCBiBHF5IMqP7zBt9xNyuAoS2Zpk4CqufpFhcGrQ93RLjSzNLOsstRjiFsGBM+RSxgqghCtGFusPTqqjXSUNxHUn9EVeVq4biTj/OHTpeWwJJf5RhJA1izVfB/D1idxskLupyop4K4kVaHX/9th22pxJ8JIN3JU=,iv:wPRZu2Xp1rOyug3Y1bSaFNs0WF2Gv09G0dJIFlU2cjE=,tag:xJIUa2+Y9Lgz4Vch24qHyQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
