apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:nmRu5PPSBKL5bAiNutWnZSuBmp12Zee0r13QGroURSGjYHRsAHlJxA4rWF2qCt9S+4SPxdg=,iv:FBzYUKzT2EOkFUgoqsvjRkHTInx602oMpd+u2VTH+3Q=,tag:+8c9ny8tcTp3uV6jr+Iceg==,type:str]
sops:
  age:
    - recipient: age16zf0xkqzqarwgrnrj8eqv2eaylnsuph2npuqq90esxzh8zt3t3zs5z3y4j
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwRVRQOTdqd3dsOWdIeFQz
        SlhCVjdzSlZhMC91d3JlRXl5aXdxMGU3RlJrCnNnd3Y1VE03dTBxWks4RlBpeVFN
        bkNBOUMwNXZKODRZQ1U2aUl6VmdnaW8KLS0tIHNGd3FRKzBoem5VUlNFUERLZzZL
        K2NCZ3FiTng4T29LRGN4S1Jzc2RON2sKrSOWT5F7Jp56oyoIE8nqd0xI28dRsY7r
        JQEEPMUCJn8do1qM7wk1zPmm1jLSiDAoeaw0wARWQNzwF4vMxQrs3w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-22T04:13:18Z"
  mac: ENC[AES256_GCM,data:fWEym13epFtF2GLQz0BMyIYPU4JYJZu0+oBv7RpMpWnBwRsoSkgs44bq0xDM3wy1uNi72M8ZbTCWlltWDHefN7k1bQ9SgFQZ2blIIeXkEVq2dsM1B15VNBgOBM4drz7m68GWq7CHgMZR65mjUdVDaAZ2DchcdekhYEe9WrjSc+0=,iv:IVRY6sZ/BsRkIT3bGv9NujU/zOzNyCbbRzc0KV38eww=,tag:QyM8SWmtwwNtIqMkkhMmIA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
